In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('new_reviews.csv')

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (0,1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
data

,Unnamed: 0,listing_id,id,date,reviewer_id,reviewer_name,comments,room_type
0,0,3781,3.777682e+07,2015-07-10,36059247.0,Greg,The apartment was as advertised and Frank was ...,Entire home/apt
1,1,3781,4.184249e+07,2015-08-09,10459388.0,Tai,It was a pleasure to stay at Frank's place. Th...,Entire home/apt
2,2,3781,4.528215e+07,2015-09-01,12264652.0,Damien,The apartment description is entirely faithful...,Entire home/apt
3,3,3781,4.902265e+07,2015-09-30,41426327.0,Mike,Thoroughly enjoyed my time at Frank's home. Ha...,Entire home/apt
4,4,3781,5.250333e+07,2015-10-30,15151513.0,Ivan,Great value for the money! This location has e...,Entire home/apt
...,...,...,...,...,...,...,...,...
129545,128306,53631121,5.144466e+17,2021-12-10,395793616.0,Hannah,Beautiful big apartment. The decor is gorgeous...,Entire home/apt
129546,128307,53631585,5.166418e+17,2021-12-13,53102978.0,Spencer,If you’re looking for luxury on a dime this hi...,Entire home/apt
129547,128308,53704154,5.158749e+17,2021-12-12,409683314.0,Reginald,great location quiet and very clean will stay ...,Entire home/apt
129548,128309,53719658,5.165859e+17,2021-12-13,241067792.0,Michael,I am very thankful that Izzy opened their hous...,Private room
129549,128310,53719658,5.188594e+17,2021-12-16,1386178.0,Vincent,Great place! Would stay again,Private room

In [6]:
with open('train_.txt', 'w', encoding='UTF-8') as f:
    for i in data['comments']:
        f.write(i+"\n")

TypeError: unsupported operand type(s) for +: 'float' and 'str'